[project]
name = "commit"
version = "0.1.0"
description = "Conventional commit cli"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "questionary>=2.1.0",
    "rich>=14.0.0",
]

[project.scripts]
commit = "commit.main:main"
